services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Core\Admin\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'

    Kazetenn\Core\Admin\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
