services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Articles\:
        resource: '../../'
            exclude:
                - '../../DependencyInjection/'
                - '../../Tests/'

