services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Admin\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'
