services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Core\Core\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'
            - '../../Entity/'

    Kazetenn\Core\Core\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
