services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kazetenn\Core\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Tests/'
            - '../../Entity/'

    Kazetenn\Core\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Kazetenn\Core\Service\ContentService:
        arguments:
            $availableContentTypes: !tagged_iterator kazetenn.content_type_tag
